server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: hishop-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hishop?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: wqde78?9gfhjk!
    druid:
      max-active: 20
      min-idle: 5
  servlet:
    multipart:
      max-file-size: 5MB
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 8
        min-idle: 8
        max-active: 8
        max-wait: -1
    timeout: 30000
  session:
    store-type: redis
  mail:
#    163 ??
#    host: smtp.163.com
#    username: bcshang95@163.com
#    password: dsa5d4562ad56s
#    protocol: smtp
#    default-encoding: UTF-8
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#            required: true
#          port: 465
#          auth: true
#          ssl:
#            enable: true

  #    QQ ??
    host: smtp.qq.com
    username: 2143728332@qq.com
    password: mpxuzxrfaviqejhe
    properties:
      mail:
        smtp:
          port: 465
          auth: true
          ssl:
            enable: true
  cloud:
    nacos:
      discovery:
        group: DEFAULT_GROUP
        server-addr: localhost:8848
        namespace: hishop

mybatis:
  typeAliasesPackage: com.onlineshop.hishop.pojo,com.onlineshop.hishop.dto.front
  mapperLocations: classpath:mapper/*Mapper.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true




