server:
  port: 8088
## 数据库设
spring:
  application:
    name: hishop-front #服务名
  cloud:
     nacos:
      discovery:
        group: DEFAULT_GROUP
        server-addr: localhost:8848
        namespace: hishop
  main:
    allow-bean-definition-overriding: true

#feign:
#  hystrix:
#    enabled: true
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE

